/* Generated by Lucky Bingo Bot. Live verified player records for Admin Panel. */
"use strict";
window.LUCKY_BINGO_ADMIN = {
  "name": "Admin Africabingooo",
  "username": "@Africabingooo",
  "phone": "+251939292694",
  "role": "Super administrator"
};
window.LUCKY_BINGO_PAYMENT_METHODS = {
  "Telebirr": {
    "name": "Telebirr",
    "account_name": "Africa Bingo",
    "account_number": "0981247219",
    "min_amount": 50,
    "bonus": "ከ 100 ETB በላይ 20% ተጨማሪ ቦነስ"
  },
  "CBE Birr": {
    "name": "CBE Birr",
    "account_name": "Africa Bingo CBE Birr",
    "account_number": "0981247219",
    "min_amount": 50,
    "bonus": "ከ 100 ETB በላይ 20% ተጨማሪ ቦነስ"
  }
};
window.LUCKY_BINGO_PLAYERS = [];
