/* Generated by Lucky Bingo Bot. Live verified player records for Admin Panel. */
"use strict";
window.LUCKY_BINGO_ADMIN = {
  "name": "0999909474",
  "username": "@samtesfa19",
  "phone": "+251939292694",
  "role": "Super administrator"
};
window.LUCKY_BINGO_PAYMENT_METHODS = {
  "Telebirr": {
    "name": "Telebirr",
    "account_name": "Africa Bingo",
    "account_number": "0999909474",
    "min_amount": 50,
    "bonus": "ከ 100 ETB በላይ 20% ተጨማሪ ቦነስ"
  },
  "CBE Birr": {
    "name": "CBE Birr",
    "account_name": "Africa Bingo CBE Birr",
    "account_number": "1000 000 000",
    "min_amount": 50,
    "bonus": "ከ 100 ETB በላይ 20% ተጨማሪ ቦነስ"
  },
  "M-Pesa": {
    "name": "M-Pesa",
    "account_name": "Africa Bingo M-Pesa",
    "account_number": "0700 000 000",
    "min_amount": 50,
    "bonus": "ከ 100 ETB በላይ 20% ተጨማሪ ቦነስ"
  }
};
window.LUCKY_BINGO_PLAYERS = [];
